hashicorp/structure

- .yarn/versions/19c1aecd.yml
- packages/pds-ember/addon/components/pds/link/docs.mdx
- packages/pds-ember/addon/components/pds/link/stories/index.stories.js
- packages/pds-ember/app/styles/pds/components/index.scss
- packages/pds-ember/app/styles/pds/components/link/_config.scss
- packages/pds-ember/app/styles/pds/components/link/index.scss
- packages/pds-ember/app/styles/pds/core/_links.scss
- packages/pds-ember/app/styles/pds/core/index.scss
- packages/pds-ember/app/styles/pds/tokens/_typography.scss
Add default link styles per PDS-154.
* `pds/core` (Sass) no longer includes core Link styles. Use `pds/components/link` instead.
> feat!(pds-ember): add Link styles

- .gitignore
- packages/pds-ember/package.json
If all goes well, Netlify should deploy Storybook docs to a PR-specific deploy preview URL.
Once this PR is merged, Netlify will deploy up-to-date Storybook docs for every commit to the `master` branch.
Docs will live at https://hashicorp-structure.netlify.app
> dev(pds-ember): update pkg scripts for Storybook via Netlify

- packages/pds-ember/.storybook/main.js
- packages/pds-ember/.storybook/preview.js
- packages/pds-ember/addon/components/pds/button/index.js
- packages/pds-ember/addon/components/pds/input/docs.mdx
- packages/pds-ember/app/styles/pds/components/code-block/index.scss
- packages/pds-ember/app/styles/pds/components/code-block/reset.scss
- packages/pds-ember/app/styles/pds/resets/index.scss
- packages/pds-ember/package.json
- packages/pds-ember/tests/dummy/app/styles/app.scss
- yarn.lock
**PDS-53**
* Part 1: (this PR) Modify storybook configs to make use of v6 features in part 2
* Part 2: #21
* **Backgrounds**: disabled
* **Viewports**: configured screen sizes using https://gs.statcounter.com/ and PDS breakpoints
* **Controls**: available, but not configured for consumption in any existing stories
> dev(pds-ember): tweak Storybook config

- packages/pds-ember/addon/components/pds/button/docs.mdx
- packages/pds-ember/addon/components/pds/button/stories/layouts/index.stories.js
- packages/pds-ember/app/styles/pds/components/button/_config.scss
* text content may wrap with lengthy content and constrained width
* [Storybook Preview](https://deploy-preview-28--hashicorp-structure.netlify.app/?path=/story/components-button-layouts--lengthy-content)
* text content should not wrap
> fix(pds-ember): prevent multi-line button content, by default

- packages/pds-ember/app/styles/pds/components/select/_config.scss
- packages/pds-ember/app/styles/pds/components/select/_control/_config.scss
- packages/pds-ember/tests/dummy/app/components/docs/form-field/select.hbs
`<select>` and `<Pds::Icon>` vertical alignment is being affected by their `line-height` (both of which are larger than `1`, so they have extra whitespace above their content, shifting elements and characters downward
> fix(pds-ember): correct line height of Pds::Select component

- packages/pds-ember/app/styles/pds/components/select/_control/_config.scss
- packages/pds-ember/app/styles/pds/utils/_property.scss
> fix(pds-ember): correct Safari styles of Select component

- packages/pds-ember/app/styles/pds/components/loading/index.scss
> fix(pds-ember): correct loading icon fill

- packages/pds-ember/addon/components/pds/app/docs.mdx
- packages/pds-ember/addon/components/pds/app/stories/index.stories.js
- packages/pds-ember/addon/components/pds/copyright/docs.mdx
- packages/pds-ember/addon/components/pds/copyright/index.hbs
- packages/pds-ember/addon/components/pds/copyright/index.js
- packages/pds-ember/addon/components/pds/copyright/stories/index.stories.js
- packages/pds-ember/addon/components/pds/global-footer/docs.mdx
- packages/pds-ember/addon/components/pds/global-footer/index.hbs
- packages/pds-ember/addon/components/pds/global-footer/index.js
- packages/pds-ember/addon/components/pds/global-footer/nav.hbs
- packages/pds-ember/addon/components/pds/global-footer/product-name.hbs
- packages/pds-ember/addon/components/pds/global-footer/stories/index.stories.js
- packages/pds-ember/app/components/pds/copyright.js
- packages/pds-ember/app/components/pds/global-footer/index.js
- packages/pds-ember/app/components/pds/global-footer/nav.js
- packages/pds-ember/app/components/pds/global-footer/product-name.js
- packages/pds-ember/app/styles/pds/components/copyright/__config.scss
- packages/pds-ember/app/styles/pds/components/copyright/index.scss
- packages/pds-ember/app/styles/pds/components/global-footer/__config.scss
- packages/pds-ember/app/styles/pds/components/global-footer/index.scss
- packages/pds-ember/app/styles/pds/components/index.scss
- packages/pds-ember/app/styles/pds/components/link/__config.scss
- packages/pds-ember/app/styles/pds/components/link/_base.scss
- packages/pds-ember/tests/integration/components/copyright/index-test.js
- packages/pds-ember/tests/integration/components/global-footer/index-test.js
JIRA: PDS-226
- Add `<Pds::Copyright>`
- Add `<Pds::GlobalFooter>`
- Update `<Pds::App>` story to demo usage of `<Pds::GlobalFooter>`
- Update App docs with cross links to relevant components
__Basic__
__Copyright + Product Name__
__Copyright + Nav__
__Copyright + Product Name + Nav__
> feat(pds-ember): add Copyright and GlobalFooter

- packages/pds-ember/addon/components/pds/empty-state/docs.mdx
- packages/pds-ember/addon/components/pds/error-state/body.hbs
- packages/pds-ember/addon/components/pds/error-state/docs.mdx
- packages/pds-ember/addon/components/pds/error-state/footer.hbs
- packages/pds-ember/addon/components/pds/error-state/index.hbs
- packages/pds-ember/addon/components/pds/error-state/index.js
- packages/pds-ember/addon/components/pds/error-state/stories/index.stories.js
- packages/pds-ember/app/components/pds/error-state/body.js
- packages/pds-ember/app/components/pds/error-state/footer.js
- packages/pds-ember/app/components/pds/error-state/index.js
- packages/pds-ember/app/styles/pds/components/error-state/__config.scss
- packages/pds-ember/app/styles/pds/components/error-state/index.scss
- packages/pds-ember/app/styles/pds/components/index.scss
- packages/pds-ember/tests/integration/components/error-state/index-test.js
(depends on #57)
- Add `<Pds::ErrorState>` component
- Add docs/examples for HTTP 403, 404, and 500 errors using the `<Pds::ErrorState>` component.
JIRA:
* PDS-225
* PDS-230
_generic example_
_HTTP 403 example_
_HTTP 404 example_
_HTTP 500 example_
> feat(pds-ember): add ErrorState

- packages/pds-ember/addon/components/pds/dropdown/dialog/index.hbs
- packages/pds-ember/addon/components/pds/dropdown/index.hbs
- packages/pds-ember/tests/integration/components/dropdown/index-test.js
This PR adds a class name to the dialog in the `Pds::Dropdown` component. This allows us to add CSS transitions on hide / show of the dialog.
> feat(pds-ember): add open modifier class to Dropdown::Dialog

- packages/pds-ember/app/styles/pds/utils/_a11y.scss
While working on https://github.com/hashicorp/waypoint/pull/1057, Rae found a bug in Firefox with the hidden radio field input being visible (in addition to the facade). This was even more obvious in dark mode because of the element's contrast. 
This is using `clip` on the `visuallyHidden` mixin, which seems to be a very common way to keep the element accessible (and it's even used in bootstrap: https://github.com/twbs/bootstrap/blob/main/scss/mixins/_visually-hidden.scss#L15), but I would welcome feedback on that.  
before: 
after:
> Fix visually hidden elements still appearing as a 1px item in Firefox

- packages/pds-ember/addon/components/pds/help-text/docs.mdx
- packages/pds-ember/addon/components/pds/help-text/index.hbs
- packages/pds-ember/addon/components/pds/help-text/index.js
- packages/pds-ember/addon/components/pds/help-text/stories/index.stories.js
- packages/pds-ember/addon/components/pds/help-text/utils.js
- packages/pds-ember/app/styles/pds/components/help-text/__config.scss
- packages/pds-ember/app/styles/pds/components/help-text/_base.scss
- packages/pds-ember/app/styles/pds/components/help-text/bold/__config.scss
- packages/pds-ember/app/styles/pds/components/help-text/bold/_config.scss
- packages/pds-ember/app/styles/pds/components/help-text/bold/index.scss
- packages/pds-ember/app/styles/pds/components/help-text/index.scss
- packages/pds-ember/package.json
The purpose of this PR is to add a bold variant to the `HelpText` component because a lot of help text on Vault Cloud uses a heavier weighted font.  It is also to set the default font weight on help text to 400 instead of 500.
> [HCPV-1090] Help Text Bold Variant

- packages/pds-ember/addon/components/pds/banner/docs.mdx
- packages/pds-ember/addon/components/pds/banner/index.js
- packages/pds-ember/addon/components/pds/banner/utils.js
- packages/pds-ember/app/styles/pds/components/banner/__config.scss
This PR adds a new type of banner, one with the warning icon but no border.
To test: Check it out under `Banner` in storybook, under `Control` there should be a Warning No Border option.
> Add warning with no border variant to banner

- packages/pds-ember/app/styles/pds/components/dropdown/item/link/__config.scss
This change allows for use of the ExternalLink component within Dropdown without the Dropdown component styling clashing with ExternalLink's styles
> Allow ExternalLink to be used within Dropdown

- packages/pds-ember/addon/components/pds/external-link/docs.mdx
- packages/pds-ember/addon/components/pds/external-link/index.hbs
- packages/pds-ember/addon/components/pds/external-link/index.js
- packages/pds-ember/addon/components/pds/external-link/stories/index.stories.js
- packages/pds-ember/tests/integration/components/external-link-test.js
These changes make the component's interface align more to that of the Button
component, and allow for an icon to be placed at the beginning or end of
the block content.
This does not contain any breaking changes. The component still defaults
to rendering the exit icon at the end of the block content as it did
prior.
> Improves ExternalLink's icon usability

- packages/pds-ember/addon/modifiers/tooltip.js
- packages/pds-ember/tests/integration/modifiers/tooltip/tooltip-test.js
- change tooltip to be a class modifier so we can control when tooltip is destroyed
- fixes issue in hcp where tooltip displaying polled data disappears after 1 sec, now it persists + updates
> HCS-2269: change tooltip to class modifier to allow updates

- packages/pds-ember/app/styles/pds/_overrides.scss
- packages/pds-ember/app/styles/pds/components/link/__config.scss
Following [the conversation in this Slack thread](https://hashicorp.slack.com/archives/CPB8GS9QT/p1656340750645769) and @jesdavpet suggestion, this PR adds the HDS classnames to the `:any-link:not(…)` CSS selector to avoid using anti-overrides to (see for example this PR https://github.com/hashicorp/cloud-ui/pull/2925) to counter the effect of that global CSS declaration on the HDS components (the declaration has a higher specificity!) 
**Notice**: I have decided to extract the CSS selectors in a Sass variable, so it can be imported via `@use` in Cloud UI. In this way it becomes a centralized place where these selectors are added/updated, without the need to manually update alsoall the local `:any-link:not(.pds-button)` declarations in Cloud UI. 
```
// needed for the …
```
> Add HDS class names to the `:any-link:not(…)` CSS selector

- packages/pds-ember/app/styles/pds/_overrides.scss
- packages/pds-ember/package.json
While testing version `2.1.0` of `@hashicorp/pds-ember` in Cloud UI I noticed one of the style was still being overwritten.
Upon further inspection, I noticed the reason was that we were selecting `.hds-dropdown-list-item--interactive` but in reality for this specific element the anchor is a child, so the right selector should be `.hds-dropdown-list-item--interactive > a`.
This small PRs fixes the selector and bumps the version as patch (I will merge without review so I am not blocked in the PR for Cloud UI, I'm confident there are no issues in the PR).
> Quick patch to fix the `hds-link-overrides-selectors` + Bump `@hashicorp/pds-ember` to version `2.1.1` 

- packages/pds-ember/.storybook/main.js
- packages/pds-ember/addon/components/pds/avatar/index.hbs
- packages/pds-ember/addon/components/pds/button/index.hbs
- packages/pds-ember/addon/components/pds/button/index.js
- packages/pds-ember/addon/components/pds/checkbox-field/facade/index.hbs
- packages/pds-ember/addon/components/pds/dropdown/trigger/index.hbs
- packages/pds-ember/addon/components/pds/error-message/index.hbs
- packages/pds-ember/addon/components/pds/select/facade.hbs
- packages/pds-ember/app/styles/pds/components/checkbox-field/facade/__config.scss
- packages/pds-ember/app/styles/pds/components/error-message/_config.scss
- packages/pds-ember/docs/install.stories.mdx
- packages/pds-ember/package.json
- packages/pds-ember/tests/dummy/app/components/docs/global-header/index.hbs
- packages/pds-ember/tests/dummy/app/templates/index.hbs
- packages/pds-ember/tests/integration/components/avatar/index-test.js
- packages/pds-ember/tests/integration/components/button/button-test.js
- packages/pds-ember/tests/integration/components/button/stories/layouts/index.stories.js
- packages/pds-ember/tests/integration/components/cta-link/stories/index.stories.js
- packages/pds-ember/tests/integration/components/dropdown/trigger/stories/index.stories.js
- packages/pds-ember/tests/integration/components/link/stories/index.stories.js
- packages/pds-ember/tests/integration/components/toolbar/stories/1_patterns.stories.js
- packages/pds-ember/tests/integration/modifiers/tooltip/docs.mdx
- packages/pds-ember/tests/integration/modifiers/tooltip/stories/index.stories.js
- yarn.lock
The intent of this PR is to remove all the usages of `Pds::Icon` _within_ the repo. Once this PR is merged a new version of Structure  will be released, adopted in Cloud UI (with the needed changes/fixes that are required by the update), and only at that point we will proceed with the complete removal and deprecation of the `Pds::Icon` component itself from the repo (this will be done in a follow-up PR, obviusly).
In this PR I have:
- **added the `@hashicorp/ember-flight-icons` package as dependency** (so we can use the `<FlightIcon>` component)
- to be able to view the icons in Storybook, we need to injected the Flight icons sprite in the Storybook page's `<head>` element; this has been done using [the `previewHead` function](https://storybook.js.org/docs/react/addons/writing-presets#prev …
> Remove `Pds:Icon` as dependency for Structure

- packages/pds-ember/app/components/pds/copyright.js
The re-export of the now-inlined `Pds::Copyright` still existed (removed [here](https://github.com/hashicorp/structure/pull/119)). This PR removes the unnecessary re-export.
> bugfix: remove re-export of the deleted copyright component

- packages/pds-ember/app/styles/pds/_overrides.scss
- packages/pds-ember/package.json
Updated the selector in `$hds-link-overrides-selectors` Sass variable to include links in `Pagination` “navigation controls”.
The component is being adopted in Cloud UI (see https://github.com/hashicorp/cloud-ui/pull/4725), but the styles conflict with the `any-link` global selector.
This small PRs updates the selector and bumps the version as patch (I will merge without review so I am not blocked in the PR for Cloud UI, I'm confident there are no issues in the PR).
> Quick patch to update the `hds-link-overrides-selectors` + Bump `@hashicorp/pds-ember` to version `2.4.1` 

- packages/pds-ember/app/styles/pds/_overrides.scss
- packages/pds-ember/package.json
Update `$hds-link-overrides-selectors` to add `hds-dropdown-list-item--variant-interactive` as we are renaming `hds-dropdown-list-item--interactive` to `hds-dropdown-list-item--variant-interactive` in https://github.com/hashicorp/design-system/pull/1185.
A follow-up PR will be raised to remove `hds-dropdown-list-item--interactive`.
[Jira ticket](https://hashicorp.atlassian.net/browse/HDS-1687)
> Update `$hds-link-overrides-selectors` and bump `@hashicorp/pds-ember` to `3.0.1`

- packages/pds-ember/app/styles/pds/_overrides.scss
- packages/pds-ember/package.json
Updated `$hds-link-overrides-selectors` to add  to include CSS class names for `SideNav` elements: 
- `.hds-side-nav__home-link`
- `.hds-side-nav__icon-button`
- `.hds-side-nav__list-item-link`
- `.ember-a11y-refocus-skip-link`
> Update `$hds-link-overrides-selectors` and bump `@hashicorp/pds-ember` to `3.0.2`
