hashicorp/structure

- packages/pds-ember/addon/components/pds/input/utils.js
- packages/pds-ember/addon/components/pds/select/utils.js
> fix(pds-ember): correct YUIDoc warnings

- packages/pds-ember/addon/components/pds/loading/docs.mdx
- packages/pds-ember/addon/components/pds/loading/elapsed/index.hbs
- packages/pds-ember/addon/components/pds/loading/elapsed/index.js
- packages/pds-ember/addon/components/pds/loading/header/index.hbs
- packages/pds-ember/addon/components/pds/loading/header/index.js
- packages/pds-ember/addon/components/pds/loading/index.hbs
- packages/pds-ember/addon/components/pds/loading/index.js
- packages/pds-ember/addon/components/pds/loading/message/index.hbs
- packages/pds-ember/addon/components/pds/loading/message/index.js
- packages/pds-ember/addon/components/pds/loading/stories/index.stories.js
- packages/pds-ember/app/components/pds/loading/elapsed.js
- packages/pds-ember/app/components/pds/loading/header.js
- packages/pds-ember/app/components/pds/loading/index.js
- packages/pds-ember/app/components/pds/loading/message.js
- packages/pds-ember/app/styles/pds/components/index.scss
- packages/pds-ember/app/styles/pds/components/loading/index.scss
- packages/pds-ember/package.json
- packages/pds-ember/public/structure-icons/loading.css
- packages/pds-ember/tests/integration/components/loading/elapsed-test.js
- packages/pds-ember/tests/integration/components/loading/header-test.js
- packages/pds-ember/tests/integration/components/loading/index-test.js
- packages/pds-ember/tests/integration/components/loading/message-test.js
- yarn.lock
Port `<Loading>` and its subcomponents from HCP, with the following differences:
1. some contextual styles previously present in HCP are not included
- `.pdsAppContent > .fullHeight .loadingState` (no context to know if it's necessary)
JIRA:
* PDS-161
* PDS-162
* PDS-163
> feat(pds-ember): add Loading component

- packages/pds-ember/addon/components/pds/definition-list/docs.mdx
- packages/pds-ember/addon/components/pds/definition-list/index.hbs
- packages/pds-ember/addon/components/pds/definition-list/index.js
- packages/pds-ember/addon/components/pds/definition-list/key/index.hbs
- packages/pds-ember/addon/components/pds/definition-list/key/index.js
- packages/pds-ember/addon/components/pds/definition-list/stories/index.stories.js
- packages/pds-ember/addon/components/pds/definition-list/value/index.hbs
- packages/pds-ember/addon/components/pds/definition-list/value/index.js
- packages/pds-ember/app/components/pds/definition-list/index.js
- packages/pds-ember/app/components/pds/definition-list/key.js
- packages/pds-ember/app/components/pds/definition-list/value.js
- packages/pds-ember/app/styles/pds/components/definition-list/__config.scss
- packages/pds-ember/app/styles/pds/components/definition-list/index.scss
- packages/pds-ember/app/styles/pds/components/definition-list/reset.scss
- packages/pds-ember/app/styles/pds/components/index.scss
- packages/pds-ember/app/styles/pds/core/typography/_config.scss
- packages/pds-ember/app/styles/pds/resets/index.scss
- packages/pds-ember/tests/integration/components/definition-list-test.js
Port component from HCP:cloud-ui-core addon.
JIRA:
* PDS-54
* PDS-98
* PDS-134
_mobile (stacked)_
_desktop (grid)_
_desktop (stacked)_
> feat(pds-ember): add DefinitionList component

- .yarn/versions/19c1aecd.yml
- packages/pds-ember/package.json
> publish(pds-ember): v0.2.0

- packages/pds-ember/app/styles/pds/theme/_light.scss
- packages/pds-ember/docs/sass/theme.stories.mdx
- add `theme.$media--xs`
- add "Sass > Theme" docs
> feat(pds-ember): add XS responsive breakpoint

- packages/pds-ember/addon/components/pds/app/stories/index.stories.js
- packages/pds-ember/addon/components/pds/link/docs.mdx
- packages/pds-ember/addon/components/pds/nav/docs.mdx
- packages/pds-ember/addon/components/pds/nav/index.hbs
- packages/pds-ember/addon/components/pds/nav/index.js
- packages/pds-ember/addon/components/pds/nav/stories/index.stories.js
- packages/pds-ember/app/components/pds/nav.js
- packages/pds-ember/app/styles/pds/components/app/_config.scss
- packages/pds-ember/app/styles/pds/components/index.scss
- packages/pds-ember/app/styles/pds/components/link/__config.scss
- packages/pds-ember/app/styles/pds/components/link/default/__config.scss
- packages/pds-ember/app/styles/pds/components/link/incognito/__config.scss
- packages/pds-ember/app/styles/pds/components/link/nav/__config.scss
- packages/pds-ember/app/styles/pds/components/link/underlined/__config.scss
- packages/pds-ember/app/styles/pds/components/nav/__config.scss
- packages/pds-ember/app/styles/pds/components/nav/index.scss
- packages/pds-ember/app/styles/pds/theme/_light.scss
- packages/pds-ember/tests/dummy/app/components/docs/nav/index.hbs
- packages/pds-ember/tests/dummy/app/templates/application.hbs
- packages/pds-ember/tests/integration/components/nav-test.js
* port applicable styles from HCP
* update `<Pds::App>` stories with nav component in place
JIRA:
* PDS-107
* PDS-174
* PDS-175
> feat(pds-ember): add Nav component

- packages/pds-ember/addon/components/pds/tab-nav/docs.mdx
- packages/pds-ember/addon/components/pds/tab-nav/index.hbs
- packages/pds-ember/addon/components/pds/tab-nav/index.js
- packages/pds-ember/addon/components/pds/tab-nav/stories/index.stories.js
- packages/pds-ember/app/components/pds/tab-nav.js
- packages/pds-ember/app/styles/pds/components/index.scss
- packages/pds-ember/app/styles/pds/components/link/tab/__config.scss
- packages/pds-ember/app/styles/pds/components/link/tab/_base.scss
- packages/pds-ember/app/styles/pds/components/link/tab/_current.scss
- packages/pds-ember/app/styles/pds/components/link/tab/_default.scss
- packages/pds-ember/app/styles/pds/components/link/tab/utils.scss
- packages/pds-ember/app/styles/pds/components/tab-nav/__config.scss
- packages/pds-ember/app/styles/pds/components/tab-nav/_top.scss
- packages/pds-ember/app/styles/pds/components/tab-nav/index.scss
- packages/pds-ember/app/styles/pds/theme/_light.scss
- packages/pds-ember/docs/guides/accessibility.stories.mdx
- packages/pds-ember/tests/integration/components/tab-nav-test.js
Branched off of #42 
JIRA: PDS-177
> feat(pds-ember): add Tabbed Nav

- packages/pds-ember/addon/components/pds/checkbox-field/docs.mdx
- packages/pds-ember/addon/components/pds/checkbox-field/facade/docs.mdx
- packages/pds-ember/addon/components/pds/checkbox-field/facade/index.hbs
- packages/pds-ember/addon/components/pds/checkbox-field/facade/index.js
- packages/pds-ember/addon/components/pds/checkbox-field/facade/stories/index.stories.js
- packages/pds-ember/addon/components/pds/checkbox-field/index.hbs
- packages/pds-ember/addon/components/pds/checkbox-field/index.js
- packages/pds-ember/addon/components/pds/checkbox-field/stories/index.stories.js
- packages/pds-ember/app/components/pds/checkbox-field/facade.js
- packages/pds-ember/app/components/pds/checkbox-field/index.js
- packages/pds-ember/app/styles/pds/components/checkbox-field/__config.scss
- packages/pds-ember/app/styles/pds/components/checkbox-field/_base.scss
- packages/pds-ember/app/styles/pds/components/checkbox-field/facade/__config.scss
- packages/pds-ember/app/styles/pds/components/checkbox-field/facade/index.scss
- packages/pds-ember/app/styles/pds/components/checkbox-field/index.scss
- packages/pds-ember/app/styles/pds/components/index.scss
- packages/pds-ember/tests/dummy/app/components/docs/checkbox-field/facade/index.hbs
- packages/pds-ember/tests/dummy/app/components/docs/checkbox-field/facade/state-table.hbs
- packages/pds-ember/tests/dummy/app/styles/_shame.scss
- packages/pds-ember/tests/dummy/app/styles/app.scss
- packages/pds-ember/tests/integration/components/checkbox-field/facade-test.js
- packages/pds-ember/tests/integration/components/checkbox-field/index-test.js
JIRA: PDS-51
_Checkbox Field Example_
_Checkbox Facade (States)_
> feat(pds-ember): add Pds::CheckboxField

- packages/pds-ember/addon/components/pds/radio-field/docs.mdx
- packages/pds-ember/addon/components/pds/radio-field/facade/docs.mdx
- packages/pds-ember/addon/components/pds/radio-field/facade/index.hbs
- packages/pds-ember/addon/components/pds/radio-field/facade/index.js
- packages/pds-ember/addon/components/pds/radio-field/facade/stories/index.stories.js
- packages/pds-ember/addon/components/pds/radio-field/index.hbs
- packages/pds-ember/addon/components/pds/radio-field/index.js
- packages/pds-ember/addon/components/pds/radio-field/stories/index.stories.js
- packages/pds-ember/app/components/pds/radio-field/facade.js
- packages/pds-ember/app/components/pds/radio-field/index.js
- packages/pds-ember/app/styles/pds/components/index.scss
- packages/pds-ember/app/styles/pds/components/radio-field/__config.scss
- packages/pds-ember/app/styles/pds/components/radio-field/_base.scss
- packages/pds-ember/app/styles/pds/components/radio-field/facade/__config.scss
- packages/pds-ember/app/styles/pds/components/radio-field/facade/index.scss
- packages/pds-ember/app/styles/pds/components/radio-field/index.scss
- packages/pds-ember/tests/dummy/app/components/docs/radio-field/facade/index.hbs
- packages/pds-ember/tests/dummy/app/components/docs/radio-field/facade/state-table.hbs
- packages/pds-ember/tests/integration/components/radio-field/facade-test.js
- packages/pds-ember/tests/integration/components/radio-field/index-test.js
(depends on #47)
JIRA: PDS-52
_Radio Field example:_
_Radio Group example:_
_Radio Facade (states):_
> feat(pds-ember): add Pds::RadioField

- packages/pds-ember/addon/components/pds/banner/body.hbs
- packages/pds-ember/addon/components/pds/banner/docs.mdx
- packages/pds-ember/addon/components/pds/banner/footer.hbs
- packages/pds-ember/addon/components/pds/banner/header.hbs
- packages/pds-ember/addon/components/pds/banner/index.hbs
- packages/pds-ember/addon/components/pds/banner/index.js
- packages/pds-ember/addon/components/pds/banner/stories/index.stories.js
- packages/pds-ember/addon/components/pds/banner/utils.js
- packages/pds-ember/app/components/pds/banner/body.js
- packages/pds-ember/app/components/pds/banner/footer.js
- packages/pds-ember/app/components/pds/banner/header.js
- packages/pds-ember/app/components/pds/banner/index.js
- packages/pds-ember/app/styles/pds/components/banner/__config.scss
- packages/pds-ember/app/styles/pds/components/banner/index.scss
- packages/pds-ember/app/styles/pds/components/index.scss
- packages/pds-ember/app/styles/pds/theme/_light.scss
- packages/pds-ember/tests/integration/components/banner/index-test.js
JIRA: PDS-189
_info_
_info-no-border_
_success_
_warning_
_error_
> feat(pds-ember): add Pds::Banner component

- packages/pds-ember/addon/components/pds/empty-state/body.hbs
- packages/pds-ember/addon/components/pds/empty-state/docs.mdx
- packages/pds-ember/addon/components/pds/empty-state/footer.hbs
- packages/pds-ember/addon/components/pds/empty-state/header.hbs
- packages/pds-ember/addon/components/pds/empty-state/index.hbs
- packages/pds-ember/addon/components/pds/empty-state/index.js
- packages/pds-ember/addon/components/pds/empty-state/stories/index.stories.js
- packages/pds-ember/app/components/pds/empty-state/body.js
- packages/pds-ember/app/components/pds/empty-state/footer.js
- packages/pds-ember/app/components/pds/empty-state/header.js
- packages/pds-ember/app/components/pds/empty-state/index.js
- packages/pds-ember/app/styles/pds/components/empty-state/__config.scss
- packages/pds-ember/app/styles/pds/components/empty-state/index.scss
- packages/pds-ember/app/styles/pds/components/index.scss
- packages/pds-ember/tests/integration/components/empty-state/index-test.js
- add `<Pds::EmptyState>`
- add `<Pds::EmptyState::Header>`
- add `<Pds::EmptyState::Body>`
- add `<Pds::EmptyState::Footer>`
JIRA: PDS-135
> feat(pds-ember): add Pds::EmptyState

- packages/pds-ember/addon/components/pds/popup/body.hbs
- packages/pds-ember/addon/components/pds/popup/docs.mdx
- packages/pds-ember/addon/components/pds/popup/footer.hbs
- packages/pds-ember/addon/components/pds/popup/header.hbs
- packages/pds-ember/addon/components/pds/popup/index.hbs
- packages/pds-ember/addon/components/pds/popup/index.js
- packages/pds-ember/addon/components/pds/popup/stories/0_index.stories.js
- packages/pds-ember/addon/components/pds/popup/stories/1_patterns.stories.js
- packages/pds-ember/addon/components/pds/popup/utils.js
- packages/pds-ember/app/components/pds/popup/body.js
- packages/pds-ember/app/components/pds/popup/footer.js
- packages/pds-ember/app/components/pds/popup/header.js
- packages/pds-ember/app/components/pds/popup/index.js
- packages/pds-ember/app/styles/pds/components/index.scss
- packages/pds-ember/app/styles/pds/components/popup/__config.scss
- packages/pds-ember/app/styles/pds/components/popup/index.scss
- packages/pds-ember/app/styles/pds/theme/_light.scss
- packages/pds-ember/tests/integration/components/popup/index-test.js
PDS-213
* Basic appearance only (with "close" action hook)
* No viewport positioning included
_Simple_
_with Body_
_with Body and Action_
_lengthy content_
_Variants_
> feat(pds-ember): add Popup

- README.md
- packages/pds-ember/CONTRIBUTING.md
- packages/pds-ember/README.md
I'm adding a little more information into the Readme based on my experiences from the last week.  Added a link from main page readme to the one with actual information, added github group information, and tips about getting storybook to work.  I have a lot of gaps in my understanding of this repo but hopefully this will help the next person add the next piece of the puzzle.
> Readme Update!

- packages/pds-ember/package.json
- packages/pds-ember/public/metadata.json
- vercel.json
- yarn.lock
This adds `sb extract` to the vercel deploy so that this storybook can be composed with other storybooks. See the docs here: https://storybook.js.org/docs/react/workflows/storybook-composition#improve-your-storybook-composition
> add sb extract to the build script

- packages/pds-ember/package.json
Includes fixes/additions to ExternalLink from  from https://github.com/hashicorp/structure/pull/83 and https://github.com/hashicorp/structure/pull/85
> Update version to 0.6.0

- packages/pds-ember/package.json
- yarn.lock
And let it float with future updates
> structure-icons 1.9.2

- packages/pds-ember/package.json
bumped Structure `@hashicorp/pds-ember` to version `0.6.4`
> Bump `@hashicorp/pds-ember` to version `0.6.4`

- packages/pds-ember/package.json
Bumped Structure `@hashicorp/pds-ember` to version `1.0.0`
> Bump `@hashicorp/pds-ember` to version `1.0.0`

- packages/pds-ember/package.json
Bumped Structure `@hashicorp/pds-ember` to version `2.0.0`
> Bump `@hashicorp/pds-ember` to version `2.0.0`

- packages/pds-ember/package.json
Bumped Structure `@hashicorp/pds-ember` to version `2.0.0`
> Bump `@hashicorp/pds-ember` to version `2.1.0`

- packages/pds-ember/package.json
Bumped Structure `@hashicorp/pds-ember` to version `2.2.0`
> Bump Structure `@hashicorp/pds-ember` to version `2.2.0`

- packages/pds-ember/package.json
Bumped Structure `@hashicorp/pds-ember` to version `2.3.0`
> Bump Structure `@hashicorp/pds-ember` to version `2.3.0`

- packages/pds-ember/package.json
Bumped Structure `@hashicorp/pds-ember` to version `2.5.0`
> Bump Structure `@hashicorp/pds-ember` to version `2.5.0`

- packages/pds-ember/package.json
Bumped Structure `@hashicorp/pds-ember` to version `3.0.0`
> Bump Structure `@hashicorp/pds-ember` to version `3.0.0`

- packages/pds-ember/package.json
Bumped Structure `@hashicorp/pds-ember` to version `4.0.0`
> Bump Structure `@hashicorp/pds-ember` to version `4.0.0`
